# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.internal: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: '@environment@'
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true


# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 720

# MyBatis Plus配置
mybatis-plus:
  # 设置id为雪花算法
  global-config:
    db-config:
      idType: ASSIGN_ID
      # 插入操作时，字段为 null 的处理策略
      insert-strategy: not_empty    # 可选值：ignored, not_null, not_empty
      # 更新操作时，字段为 null 的处理策略
      update-strategy: ignored    # 可选值：ignored, not_null, not_empty
  # 搜索指定包别名
  typeAliasesPackage: com.internal.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api
knife4j:
  enable: true
  setting:
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

system:
  domainName: 'http://192.168.7.143:8088/'
  syncProjectSystemSendEmail: 'A1225172983@163.com'
  syncProjectSystemSendEmailHost: 'smtp.163.com'
  syncProjectSystemSendEmailPassword: 'DCQJK962tYKf7aer'
  # crmProjectSyncUrl       见子配置文件
  # syncProjectManagerEmail 见子配置文件
  # syncProjectManagerName  见子配置文件
  send:
    email:
      nickname: nl
